### ISSUE TITLE
vauth can't recognize (but receive) vm start event

### ISSUE THREAD

**Issue by tgreat72** [martezr/vauth#13]
Hi,

for me the vauth can't recognize the vm start/restart and doesn't get the role/secret id from vault.

However when I change the value of the custom attr `vauth-role`, on a running vm, it works and I can find the IDs in guest info, so there is no connection issue,.

```
2022/10/17 14:08:01 detected custom attribute change event for XXX
2022/10/17 14:08:01 found the  role associated with XXX
2022/10/17 14:08:01 no role associated with XXX
2022/10/17 14:08:01 vm record added: {"name":"XXX","latest_event_id":"7737772","role":""}
2022/10/17 14:10:09 detected custom attribute change event for XXX
2022/10/17 14:10:09 found the YYY role associated with XXX
2022/10/17 14:10:09 updated VM: XXX
2022/10/17 14:10:09 vm record added: {"name":"XXX","latest_event_id":"7737782","role":"YYY"}
2022/10/17 15:05:30 detected custom attribute change event for XXX
2022/10/17 15:05:31 found the  role associated with XXX
2022/10/17 15:05:31 no role associated with XXX
2022/10/17 15:05:31 vm record added: {"name":"XXX","latest_event_id":"7738243","role":""}
2022/10/17 15:05:40 detected custom attribute change event for XXX
2022/10/17 15:05:41 found the YYY role associated with XXX
2022/10/17 15:05:41 updated VM: XXX
2022/10/17 15:05:41 vm record added: {"name":"XXX","latest_event_id":"7738245","role":"YYY"}
```

`tcpdump` shows that during vm operations (start/stop) there is traffic between the vauth and vcenter

Interesting, it can "see" the deletions:

```
2022/10/15 13:07:51 detected remove event for XXX
2022/10/15 13:07:51 Delete VM: XXX
```

**Comment by martezr** [comment]
@tgreat72 What version of vSphere are you running? It looks like the debug flag I was considering adding to output all events is necessary for cases like this.

**Comment by martezr** [comment]
Disregard, it looks like it is because the VM is in a cluster with DRS which is a slightly different event (DrsVmPoweredOnEvent) than what was previously coded. Support is being added for this additional event type.

**Comment by tgreat72** [comment]
> @tgreat72 What version of vSphere are you running? It looks like the debug flag I was considering adding to output all events is necessary for cases like this.

for the record, vspherr version 7.0.3 and yes, we use RDS.

without RDS it is working fine:
```
vauth-vauth-1  | 2022/10/18 10:31:50 detected power on event for XXX
vauth-vauth-1  | 2022/10/18 10:31:50 found the YYY role associated with XXX
vauth-vauth-1  | 2022/10/18 10:31:50 updated VM: XXX
vauth-vauth-1  | 2022/10/18 10:31:50 vm record added: {"name":"XXX","latest_event_id":"7749434","role":"YYY","datacenter":"AAA"}
```

**Comment by martezr** [comment]
The code has been updated in the latest release(v0.0.2) to support DRS power on events.
